# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

env:
  global:
    - CORE_RELEASE=master

matrix:
  include:
    - php: 5.5
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 5.5
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 5.5
      env: DB=SQLITE PHPUNIT_TEST=1
    - php: 5.6
      env: DB=MYSQL PDO=1 PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL PDO=1 PHPUNIT_COVERAGE_TEST=1

before_script:
    - composer self-update || true
    - phpenv rehash
    - phpenv config-rm xdebug.ini
    - git clone -b "pulls/alias-and-installer-branch" git://github.com/chillu/silverstripe-travis-support.git ~/travis-support
    - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
    - cd ~/builds/ss

script:
    - "if [ \"$PHPUNIT_TEST\" = \"1\" ]; then vendor/bin/phpunit reports/tests; fi"
    - "if [ \"$PHPUNIT_COVERAGE_TEST\" = \"1\" ]; then phpdbg -qrr vendor/bin/phpunit reports/tests --coverage-clover=coverage.xml; fi"
    - "if [ \"$PHPUNIT_COVERAGE_TEST\" = \"1\" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi"
